apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher-projector-sa
  namespace: kube-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rancher-projector-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    #verbs: ["list", "watch", "get"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher-projector-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rancher-projector-role
subjects:
  - kind: ServiceAccount
    name: rancher-projector-sa
    namespace: kube-system
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-projector
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-projector
  template:
    metadata:
      labels:
        app: rancher-projector
    spec:
      serviceAccountName: rancher-projector-sa
      containers:
        - name: rancher-projector
          image: wrkode/rancher-projector:dev
          imagePullPolicy: Always
          env:
            - name: BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rancher-projector-secret
                  key: token
            - name: RANCHER_FQDN
              value: "rancher.lab.k8"
            - name: skipTLSVerify
              value: "true"
